#!/usr/bin/env bash
set -a
source /etc/default/bisq-seednode.env
set +a

export BISQ_DATA_DIR=$BISQ_HOME/$BISQ_APP_NAME/$BISQ_BASE_CURRENCY
export BISQ_JSON_DIR=$BISQ_DATA_DIR/db/json
export BSQ_EXPLORER_ROOT=$BISQ_HOME/bisq-explorer/www

while inotifywait -r -e modify,move,create,delete "${BISQ_JSON_DIR}"
do
    echo "Bisq has updated JSON data dump for BSQ transactions!"
    sleep 5
    echo "Syncing JSON from Bisq ${BISQ_JSON_DIR} to ${BSQ_EXPLORER_ROOT}/data/"
    rsync -rt --exclude '*.tmp' "${BISQ_JSON_DIR}" "${BSQ_EXPLORER_ROOT}/data/"
    echo "Re-indexing BSQ Explorer webroot"
    /usr/local/bin/bsq-index
done
